### ISSUE TITLE
KeyError: "Unable to open object (object 'cis_indices' doesn't exist)"

### ISSUE THREAD

**Issue by MogicianEik** [bxlab/hifive#12]
Hi, sorry for bothering. I am using your package as part of my Hi-C analysis pipeline. I will just show the code and the error and see if you have some clues.
Code: 
`# Filtering HiC fends
 hic = hifive.HiC('HiC_project_object.hdf5')
 hic.filter_fends(mininteractions=1, mindistance=0, maxdistance=0)
 hic.save()
`
Error:
>>> execfile('HiCtool_hifive.py')                                 │                                                                  
Loading data from HiCfile_pair1.bam... Done                       │                                                                  
Read 0 validly-mapped read pairs.                                 │                                                                  
No valid data was loaded.                                         │                                                                  
Filtering fends...Traceback (most recent call last):              │                                                                  
  File "<stdin>", line 1, in <module>                             │                                                                  
  File "HiCtool_hifive.py", line 75, in <module>                  │                                                                  
    hic.filter_fends(mininteractions=1, mindistance=0, maxdistance│                                                                  
=0)                                                               │                                                                  
  File "/home/lisky/.local/lib/python2.7/site-packages/hifive/hic.│                                                                  
py", line 357, in filter_fends                                    │                                                                  
    data = self.data['cis_data'][...]                             │                                                                  
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wr│                                                                  
apper                                                             │                                                                  
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wr│                                                                  
apper                                                             │                                                                  
  File "/home/lisky/.local/lib/python2.7/site-packages/h5py/_hl/gr│                                                                  
oup.py", line 262, in __getitem__                                 │                                                                  
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)       │                                                                  
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wr│                                                                  
apper                                                             │                                                                  
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wr│                                                                  
apper                                                             │                                                                  
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open                 │                                                                  
KeyError: "Unable to open object (object 'cis_data' doesn't exist)│         
"
Looking for your reply, many Thanks

**Comment by MogicianEik** [comment]
Hi msauria, it looks like the hdf5 file was failed to load. Currently this problem remains.

**Comment by MogicianEik** [comment]
Hi msauria, after checking functions unit by unit, I think these codes did not function properly:
`data = hifive.HiCData('HiC_data_object.hdf5', mode='w')
data.load_data_from_bam('fend_object.hdf5',
                        [bam_file_1,bam_file_2], 
                        maxinsert=500,
                        skip_duplicate_filtering=False)
data.save()`
because sizes of my bam files are 
-rw-r--r-- 1 lisky cbi  8906404241 Jan  9 19:43 HiCfile_pair1.bam
-rw-r--r-- 1 lisky cbi 10378322287 Jan  9 23:24 HiCfile_pair2.bam
but the HiCData object is only
-rw-r--r-- 1 lisky cbi        7472 Jan 11 13:50 HiC_data_object.hdf5
